### PR TITLE
fix: stencil-one additional fixes

### PR DESCRIPTION
**Pull request by mikaelkaron**
- remove use of deprecated `JSX` import
- remove conflicting declarations
- update documentation configuration option

### CODE REVIEW

**Comment by hiebj** [comment]
Can we please get this reviewed and merged? I am having the same problem with `inlist` and functional components, using this patch solves it for me

**Comment by DaSchTour** [comment]
Is there any possibility to speed this up? It's hanging around here for 1,5 years and it's blocking my development.

**Comment by hiebj** [comment]
> Is there any possibility to speed this up? It's hanging around here for 1,5 years and it's blocking my development.

@DaSchTour I wrote a decorator called `@Subscribed()` to drop the last value of an `Observable` into a `@State()` property, and got rid of `stencil-apollo`, for this very reason.

**Comment by DaSchTour** [comment]
@hiebj yeah I also simply used Apollo Client programmatically inside my components. The main reason for using stencil-apollos was that I'm using codgen from my graphql files. But it also works fine by using the generated documents.

**Pull request closed without merging**
